name: Test

on:
  push:
    branches:
      - main
      - develop
      - develop2
  pull_request:
    branches:
      - main
      - develop
      - develop2
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC every day

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, macos-12, macos-11, windows-2022, windows-2019]
        compiler: [gcc] #, intel]
        version: [12, 11, 10, 9, 8, 7, 6, 5]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Fortran
        continue-on-error: true
        id: setup-fortran
        uses: ./
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check compiler version
        if: steps.setup-fortran.outcome == 'success'
        shell: bash
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
          CC: ${{ steps.setup-fortran.outputs.cc }}
        run: |
          fcv=$(${{ env.FC }} --version | head -n 1)
          ccv=$(${{ env.CC }} --version | head -n 1)
          
          echo $fcv
          echo $ccv
          
          fcv=$(echo "${fcv##*)}" | xargs)
          ccv=$(echo "${ccv##*)}" | xargs)
          
          [[ $fcv == ${{ matrix.version }}* ]] || (echo "unexpected Fortran compiler version: $fcv"; exit 1)
          [[ $ccv == ${{ matrix.version }}* ]] || (echo "unexpected C compiler version: $ccv"; exit 1)

      - name: Test compile program (bash)
        if: steps.setup-fortran.outcome == 'success'
        shell: bash
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
          CC: ${{ steps.setup-fortran.outputs.cc }}
        run: |
          ${{ env.FC }} -o hw test/hw.f90
          output=$(./hw '2>&1')
          [[ "$output" == *"hello world"* ]] && echo "$output" || (echo "Unexpected output: $output"; exit 1)

      - name: Test compile program (pwsh)
        if: steps.setup-fortran.outcome == 'success' && runner.os == 'Windows'
        shell: pwsh
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
          CC: ${{ steps.setup-fortran.outputs.cc }}
        run: |
          rm hw.exe
          ${{ env.FC }} -o hw.exe test\hw.f90 
          $output=$(& ".\hw.exe")
          if ($output -match "hello world") {
              write-output $output
          } else {
              write-output "unexpected output: $output"
              exit 1
          }

      - name: Test compile program (cmd)
        if: steps.setup-fortran.outcome == 'success' && runner.os == 'Windows'
        shell: cmd
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
          CC: ${{ steps.setup-fortran.outputs.cc }}
        run: |
          del hw.exe
          ${{ env.FC }} -o hw.exe test\hw.f90 
          for /f "tokens=* usebackq" %%f in (`.\hw.exe`) do @set "OUTPUT=%%f"
          if "%OUTPUT%"=="hello world" (
            echo "%OUTPUT%"
          ) else (
            echo "unexpected output: %OUTPUT%"
            exit 1
          )
