name: Test
# Workflow has two modes: assert and report
# Push and pull request run in assert mode.
# Schedule and dispatch run in report mode.
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop*
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  options:
    name: Set options
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.mode.outputs.mode }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect mode
        id: mode
        run: |
          if [[ "$trigger" == "schedule" ]] || [[ "$trigger" == "workflow_dispatch" ]]; then
            echo "mode=report" >> "$GITHUB_OUTPUT"
          else
            echo "mode=assert" >> "$GITHUB_OUTPUT"
          fi
          echo "mode=report" >> "$GITHUB_OUTPUT"

      - name: Set matrix
        working-directory: .github/compat
        id: matrix
        run: |
          mode=${{ steps.mode.outputs.mode }}
          if [[ "$mode" == "report" ]]; then
            yq -o json matrix.yml > matrix.json
          else
            python matrix_json_from_csv.py "long_compat.csv" "matrix.json"
          fi
          matrix=$(cat matrix.json | jq -r tostring | sed -e 's/"/\\"/g')
          echo $matrix
          echo ${{ toJSON(fromJSON('{"os":["ubuntu-22.04","ubuntu-20.04","macos-13","macos-12","macos-11","windows-2022","windows-2019"],"toolchain":[{"compiler":"gcc","version":13},{"compiler":"gcc","version":12},{"compiler":"gcc","version":11},{"compiler":"gcc","version":10},{"compiler":"gcc","version":9},{"compiler":"gcc","version":8},{"compiler":"gcc","version":7},{"compiler":"gcc","version":6},{"compiler":"intel","version":"2023.2"},{"compiler":"intel","version":"2023.1"},{"compiler":"intel","version":"2023.0"},{"compiler":"intel","version":"2022.2.1"},{"compiler":"intel","version":"2022.2"},{"compiler":"intel","version":"2022.1"},{"compiler":"intel","version":"2022.0"},{"compiler":"intel","version":"2021.4"},{"compiler":"intel","version":"2021.2"},{"compiler":"intel","version":"2021.1.2"},{"compiler":"intel","version":"2021.1"},{"compiler":"intel-classic","version":"2021.10"},{"compiler":"intel-classic","version":"2021.9"},{"compiler":"intel-classic","version":"2021.8"},{"compiler":"intel-classic","version":"2021.7.1"},{"compiler":"intel-classic","version":"2021.7"},{"compiler":"intel-classic","version":"2021.6"},{"compiler":"intel-classic","version":"2021.5"},{"compiler":"intel-classic","version":"2021.4"},{"compiler":"intel-classic","version":"2021.3"},{"compiler":"intel-classic","version":"2021.2"},{"compiler":"intel-classic","version":"2021.1.2"},{"compiler":"intel-classic","version":"2021.1"},{"compiler":"nvidia-hpc","version":"23.11"},{"compiler":"nvidia-hpc","version":"23.9"},{"compiler":"nvidia-hpc","version":"23.7"},{"compiler":"nvidia-hpc","version":"23.5"},{"compiler":"nvidia-hpc","version":"23.3"},{"compiler":"nvidia-hpc","version":"23.1"},{"compiler":"nvidia-hpc","version":"22.11"},{"compiler":"nvidia-hpc","version":"22.9"},{"compiler":"nvidia-hpc","version":"22.7"},{"compiler":"nvidia-hpc","version":"22.5"},{"compiler":"nvidia-hpc","version":"22.3"},{"compiler":"nvidia-hpc","version":"22.2"},{"compiler":"nvidia-hpc","version":"22.1"},{"compiler":"nvidia-hpc","version":"21.11"},{"compiler":"nvidia-hpc","version":"21.9"},{"compiler":"nvidia-hpc","version":"21.7"},{"compiler":"nvidia-hpc","version":"21.5"},{"compiler":"nvidia-hpc","version":"21.3"},{"compiler":"nvidia-hpc","version":"21.2"},{"compiler":"nvidia-hpc","version":"21.1"},{"compiler":"nvidia-hpc","version":"20.11"},{"compiler":"nvidia-hpc","version":"20.9"},{"compiler":"nvidia-hpc","version":"20.7"}],"exclude":[{"os":"macos-13","toolchain":{"compiler":"intel"}},{"os":"macos-12","toolchain":{"compiler":"intel"}},{"os":"macos-11","toolchain":{"compiler":"intel"}},{"os":"macos-13","toolchain":{"compiler":"nvidia-hpc"}},{"os":"macos-12","toolchain":{"compiler":"nvidia-hpc"}},{"os":"macos-11","toolchain":{"compiler":"nvidia-hpc"}},{"os":"windows-2022","toolchain":{"compiler":"nvidia-hpc"}},{"os":"windows-2019","toolchain":{"compiler":"nvidia-hpc"}}]}')) }}
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
    
  test:
    name: Test
    needs: options
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.options.outputs.matrix) }}
      # matrix:
      #   os:
      #     - ubuntu-22.04
      #     - ubuntu-20.04
      #     - macos-13
      #     - macos-12
      #     - macos-11
      #     - windows-2022
      #     - windows-2019
      #   toolchain:
      #     - {compiler: gcc, version: 13}
      #     - {compiler: gcc, version: 12}
      #     - {compiler: gcc, version: 11}
      #     - {compiler: gcc, version: 10}
      #     - {compiler: gcc, version:  9}
      #     - {compiler: gcc, version:  8}
      #     - {compiler: gcc, version:  7}
      #     - {compiler: gcc, version:  6}
      #     - {compiler: intel, version: '2023.2'}
      #     - {compiler: intel, version: '2023.1'}
      #     - {compiler: intel, version: '2023.0'}
      #     - {compiler: intel, version: '2022.2.1'}
      #     - {compiler: intel, version: '2022.2'}
      #     - {compiler: intel, version: '2022.1'}
      #     - {compiler: intel, version: '2022.0'}
      #     - {compiler: intel, version: '2021.4'}
      #     - {compiler: intel, version: '2021.2'}
      #     - {compiler: intel, version: '2021.1.2'}
      #     - {compiler: intel, version: '2021.1'}
      #     - {compiler: intel-classic, version: '2021.10'}
      #     - {compiler: intel-classic, version: '2021.9'}
      #     - {compiler: intel-classic, version: '2021.8'}
      #     - {compiler: intel-classic, version: '2021.7.1'}
      #     - {compiler: intel-classic, version: '2021.7'}
      #     - {compiler: intel-classic, version: '2021.6'}
      #     - {compiler: intel-classic, version: '2021.5'}
      #     - {compiler: intel-classic, version: '2021.4'}
      #     - {compiler: intel-classic, version: '2021.3'}
      #     - {compiler: intel-classic, version: '2021.2'}
      #     - {compiler: intel-classic, version: '2021.1.2'}
      #     - {compiler: intel-classic, version: '2021.1'}
      #     - {compiler: nvidia-hpc, version: '23.11'}
      #     - {compiler: nvidia-hpc, version: '23.9'}
      #     - {compiler: nvidia-hpc, version: '23.7'}
      #     - {compiler: nvidia-hpc, version: '23.5'}
      #     - {compiler: nvidia-hpc, version: '23.3'}
      #     - {compiler: nvidia-hpc, version: '23.1'}
      #     - {compiler: nvidia-hpc, version: '22.11'}
      #     - {compiler: nvidia-hpc, version: '22.9'}
      #     - {compiler: nvidia-hpc, version: '22.7'}
      #     - {compiler: nvidia-hpc, version: '22.5'}
      #     - {compiler: nvidia-hpc, version: '22.3'}
      #     - {compiler: nvidia-hpc, version: '22.2'}
      #     - {compiler: nvidia-hpc, version: '22.1'}
      #     - {compiler: nvidia-hpc, version: '21.11'}
      #     - {compiler: nvidia-hpc, version: '21.9'}
      #     - {compiler: nvidia-hpc, version: '21.7'}
      #     - {compiler: nvidia-hpc, version: '21.5'}
      #     - {compiler: nvidia-hpc, version: '21.3'}
      #     - {compiler: nvidia-hpc, version: '21.2'}
      #     - {compiler: nvidia-hpc, version: '21.1'}
      #     - {compiler: nvidia-hpc, version: '20.11'}
      #     - {compiler: nvidia-hpc, version: '20.9'}
      #     - {compiler: nvidia-hpc, version: '20.7'}
      #   exclude:
      #     # ifx not available for mac
      #     - os: macos-13
      #       toolchain: {compiler: intel}
      #     - os: macos-12
      #       toolchain: {compiler: intel}
      #     - os: macos-11
      #       toolchain: {compiler: intel}
      #     # nvidia-hpc not available for mac
      #     - os: macos-13
      #       toolchain: {compiler: nvidia-hpc}
      #     - os: macos-12
      #       toolchain: {compiler: nvidia-hpc}
      #     - os: macos-11
      #       toolchain: {compiler: nvidia-hpc}
      #     # nvidia-hpc not available for windows
      #     - os: windows-2022
      #       toolchain: {compiler: nvidia-hpc}
      #     - os: windows-2019
      #       toolchain: {compiler: nvidia-hpc}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fortran
        id: setup-fortran
        continue-on-error: true
        uses: ./
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Test Fortran compiler
        if: steps.setup-fortran.outcome == 'success'
        uses: ./.github/actions/test-fc
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      
      - name: Test C compiler
        continue-on-error: true
        if: steps.setup-fortran.outcome == 'success'
        uses: ./.github/actions/test-cc
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      
      - name: Test C++ compiler
        continue-on-error: true
        if: steps.setup-fortran.outcome == 'success'
        uses: ./.github/actions/test-cxx
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Create compatibility report
        shell: bash
        run: |
          mkdir -p compat
          support=$([ "${{ steps.setup-fortran.outcome }}" == "success" ] && echo "&check;" || echo "")
          prefix="${{ matrix.os }},${{ matrix.toolchain.compiler }},${{ matrix.toolchain.version }}"
          report="compat/${prefix//,/_}.csv"
          echo "$prefix,$support" >> "$report"
          cat "$report"

      - name: Upload compatibility report
        uses: actions/upload-artifact@v3
        with:
          name: compat
          path: compat/*.csv
  
  compat:
    name: Assert and/or report compatibility
    needs: 
      - options
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: compat
          path: compat

      - name: Concatenate reports
        run: |
          echo "runner,compiler,version,support" > .github/compat/long_compat.csv
          cat compat/*.csv >> .github/compat/long_compat.csv

      - name: Make wide reports
        working-directory: .github/compat
        run: |
          python wide_compat_reports.py "long_compat.csv" "compat.csv"
          cat compat.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compat
          path: |
            .github/compat/long_compat.csv
            .github/compat/compat.csv
            .github/compat/compat.md

      - name: Check for changes
        working-directory: .github/compat
        id: diff
        run: |
          if ! [ -f compat.csv ]; then
            echo "diff=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          diff=$(git diff compat.csv)
          if [[ $diff == "" ]]; then
            echo "No changes found"
            echo "diff=false" >> $GITHUB_OUTPUT
          else
            echo "Changes found:"
            echo "$diff"
            echo "diff=true" >> $GITHUB_OUTPUT
            if [[ "${{ needs.options.outputs.mode }}" == "assert" ]]; then
              exit 1
            fi
          fi

      - name: Update README
        if: ${{ steps.diff.outputs.diff == 'true' && github.event_name == 'push' }}
        run: python .github/compat/update_compat_table.py ".github/compat/compat.md" "README.md"

      - name: Print README diff
        if: ${{ steps.diff.outputs.diff == 'true' && github.event_name == 'push' }}
        run: git diff README.md

      - name: Create pull request
        if: ${{ steps.diff.outputs.diff == 'true' && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          now=$(date +'%Y-%m-%dT%H-%M-%S')
          updated_branch="compat_$now"
          default_branch="${{ github.event.repository.default_branch }}"
          
          git switch -c "$updated_branch"
          git add .github/compat/compat.csv README.md
          git commit -m "Update compatibility matrix"
          git push -u origin "$updated_branch"
          gh pr create -B "$default_branch" -H "$updated_branch" --title "Update compatibility matrix" --body-file .github/compat/compat.md
