name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC every day

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, macos-12, macos-11, windows-2022, windows-2019]
        compiler: [gcc]
        version: [12, 11, 10, 9, 8, 7, 6, 5]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Fortran
        id: setup-fortran
        uses: ./
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Check compiler version
        shell: bash
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
          CC: ${{ steps.setup-fortran.outputs.cc }}
        run: |
          fcv=$(${{ env.FC }} --version | head -n 1)
          ccv=$(${{ env.CC }} --version | head -n 1)
          
          echo $fcv
          echo $ccv
          
          fcv=${fcv##* }
          ccv=${ccv##* }
          
          [[ $fcv == ${{ matrix.version }}* ]] || (echo "unexpected Fortran compiler version: $fcv"; exit 1)
          [[ $ccv == ${{ matrix.version }}* ]] || (echo "unexpected C compiler version: $ccv"; exit 1)

      - name: Test compile program (bash)
        continue-on-error: true
        shell: bash
        run: |
          gfortran -o hw test/hw.f90
          output=$(./hw '2>&1')
          [[ "$output" == *"hello world"* ]] && echo "$output" || (echo "Unexpected output: $output"; exit 1)

      - name: Test compile program (pwsh)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          rm hw.exe
          gfortran -o hw.exe test\hw.f90 
          $output=$(& ".\hw.exe")
          if ($output -match "hello world") {
              write-output $output
          } else {
              write-output "unexpected output: $output"
              exit 1
          }

      - name: Test compile program (cmd)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          del hw.exe
          gfortran -o hw.exe test\hw.f90 
          for /f "tokens=* usebackq" %%f in (`.\hw.exe`) do @set "OUTPUT=%%f"
          if "%OUTPUT%"=="hello world" (
            exit 0
          ) else (
            echo "unexpected output: %OUTPUT%"
            exit 1
          )
